name: ci

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run Rspec
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake
